### ISSUE TITLE
TWRP for NX606J

### ISSUE THREAD

**Issue by Crossader** [youyim123/android_device_nubia_nx606j#1]
Hi youyim123,

did you succeed in creating the device tree, building the TWRP and flash it to the NX606J? If so, could you share the recovery.img, please?

Thank you!

**Comment by curtisy1** [comment]
I'm working on it. Compiling itself isn't that hard (instructions in the readme), same for flashing (also in the readme). The problem I'm currently trying to solve is the last sentence in Chinese. From Google translate it says that the phone uses avb2.0 (Android verified boot) and since the keys aren't included, the image won't work (can confirm, it says the boot is corrupted if flashed)..

So what I'm currently trying is to port Omni to this and override any existing stuff instead of working around this issue. However I'm no expert and mostly going from error to error, so this might take a while..

**Comment by Crossader** [comment]
So there's no working TWRP available yet.
@curtisy1: Thank you for the Information, so I'll also try to port omni and inform you about the effort.

**Comment by curtisy1** [comment]
> This keys are not public, so I can't give it to you.

No worries, you don't have to. Your work is already an amazing help as it is <3
I would be able to grab the keys from the device though if I'm assuming correctly? (Even if I can't I wouldn't need them for an omni/lineage port, would I?)

**Comment by curtisy1** [comment]
@Crossader do you perhaps have Discord? I'd very much like some help as I'm not an expert in any of this and maybe it's my environment I'm compiling on that hinders me here.. I'd gladly share my current progress with you so you don't have to start from scratch (and maybe see where my error is)

**Comment by Crossader** [comment]
Hi youyim123,
I read about your effort on bbs.nubia.cn
Did you already release the TWRP? I also read your discussion about your interlectual property and ensure that I'll respect it. 
Thank you very much!

**Comment by curtisy1** [comment]
@Crossader if you're interested in taking this, try using the test keys that come with aosp. I read they should also work since they're debugging keys.

**Comment by youyim123** [comment]
> > This keys are not public, so I can't give it to you.
> 
> No worries, you don't have to. Your work is already an amazing help as it is <3
> I would be able to grab the keys from the device though if I'm assuming correctly? (Even if I can't I wouldn't need them for an omni/lineage port, would I?)

https://github.com/youyim123/android_device_nubia_nx606j/releases/download/test/recovery.img
